### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pmw9027** [schulzch/ted-js#2]
How to use this library as native javascript?

**Comment by schulzch** [comment]
Grab the compiled [edit-distance.js](https://github.com/schulzch/edit-distance-js/releases/download/v1.0.0/edit-distance.js) from the releases page, include it in your page, then follow the process in the readme, i.e.:

```html
<script src="edit-distance.js"></script>
<script>
var ed = global.editDistance;
// your code here
</script>
```
